version: "3.10"

services:
  redis:
    image: redis:alpine
    restart: unless-stopped
    healthcheck:
      test: redis-cli ping | grep PONG
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 128M
    security_opt:
      - no-new-privileges:true

  rabbit-mq:
    image: rabbitmq:3.10-management-alpine
    restart: unless-stopped
    healthcheck:
      test: rabbitmq-diagnostics -q ping
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 525M
    security_opt:
      - no-new-privileges:true

  jasmin:
    hostname: jasmin
    image: jookies/jasmin:latest
    restart: unless-stopped
    ports:
      - 2775:2775
      - 8990:8990
      - 1401:1401
    depends_on:
      redis:
        condition: service_healthy
      rabbit-mq:
        condition: service_healthy
    environment:
      REDIS_CLIENT_HOST: redis
      AMQP_BROKER_HOST: rabbit-mq
    healthcheck:
      disable: true
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 256M
    security_opt:
     - no-new-privileges:true

  jasmin_log:
    image: tarekaec/jasmin_log:1.0
    restart: unless-stopped
    command: /usr/local/bin/python -m pip install psycopg2 mysql-connector-python
    # entrypoint: ./sms_logger.py
    depends_on:
      rabbit-mq:
        condition: service_healthy
    environment:
      AMQP_BROKER_HOST: rabbit-mq
      DB_TYPE_MYSQL: '0'
      DB_HOST: '172.17.0.1'  # Set the correct ip or host name
      DB_DATABASE: 'jasmin_web_db'
      DB_TABLE: 'submit_log'
      DB_USER: 'postgres'
      DB_PASS: '123'
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 256M
    security_opt:
     - no-new-privileges:true

  jasmin_web:
    image: tarekaec/jasmin_web_panel:1.1
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      redis:
        condition: service_healthy
#      jasmin:
#        condition: service_healthy
    environment:
      JASMIN_PORT: 8000
    healthcheck:
      disable: true
    volumes:
      - ./public:/jasmin/public
    entrypoint: /jasmin/docker-entrypoint.sh
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '1'
          memory: 256M
